/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

/**
 *
 * @author fernan
 */
public class VistaGestionDeProductos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaGestionDeProductos.class.getName());
    private int idSucursal;
    private String nombreUsuario;
    /**
     * Creates new form VistaGestionDeProductos
     */
    public VistaGestionDeProductos(int idSucursal) {
        initComponents();
        this.idSucursal= idSucursal;
        cargarProductos();
        this.setLocationRelativeTo(null);
    }
    private void cargarProductos(){
        PartesLogicas.ProductoDAO dao = new PartesLogicas.ProductoDAO();
        java.util.List<PartesLogicas.Producto> lista = dao.obtenerProductosPorSucursal(idSucursal);
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Activo");
        
        for(PartesLogicas.Producto p : lista){
            modelo.addRow(new Object[]{
                p.getId(),
                p.getNombre(),
                p.getDescripcion(),
                p.isActivo() ? "Activo":"Desactivado"
            });
        }
        tablaProductos.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        btnCrearProducto = new javax.swing.JButton();
        btnProducto = new javax.swing.JButton();
        btnDesactivarProductos = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 620, 550));

        btnCrearProducto.setText("Crear");
        btnCrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProductoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 710, 100, 40));

        btnProducto.setText("Modificar Producto");
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });
        getContentPane().add(btnProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 710, -1, 40));

        btnDesactivarProductos.setText("Activar / Desactivar");
        btnDesactivarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarProductosActionPerformed(evt);
            }
        });
        getContentPane().add(btnDesactivarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 710, 160, 40));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 710, 100, 40));

        jLabel1.setText("GESTION DE PRODUCTOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 830, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 690, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProductoActionPerformed
        // TODO add your handling code here:
        String nombre = javax.swing.JOptionPane.showInputDialog(this, "Nombre del producto: ");
        if(nombre == null || nombre.trim().isEmpty())return;
        
        String descripcion = javax.swing.JOptionPane.showInputDialog(this, "Descripcion: ");
        if(descripcion == null) descripcion = "";
        
        PartesLogicas.ProductoDAO dao = new PartesLogicas.ProductoDAO();
        dao.crearProductos(nombre, descripcion, idSucursal);
        cargarProductos();
    }//GEN-LAST:event_btnCrearProductoActionPerformed

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
        // TODO add your handling code here:
        int fila = tablaProductos.getSelectedRow();
        if(fila == -1){
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un producto");
            return;
        }
        int idProducto = (int) tablaProductos.getValueAt(fila, 0);
        
        String nuevoNombre = javax.swing.JOptionPane.showInputDialog(this, "Nuevo nombre: ");
        if(nuevoNombre == null || nuevoNombre.trim().isEmpty()) return;
        
        String nuevaDescripcion = javax.swing.JOptionPane.showInputDialog(this, "Nueva descripcion: ");
        if(nuevaDescripcion == null) nuevaDescripcion="";
        PartesLogicas.ProductoDAO dao = new PartesLogicas.ProductoDAO();
        dao.modificarProducto(idProducto, nuevoNombre, nuevaDescripcion);
        
        cargarProductos();
        
    }//GEN-LAST:event_btnProductoActionPerformed

    private void btnDesactivarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarProductosActionPerformed
        int fila = tablaProductos.getSelectedRow();
        if(fila == -1){
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un producto");
        return;
        }

        int idProducto = (int) tablaProductos.getValueAt(fila, 0);
        String estadoTexto = (String) tablaProductos.getValueAt(fila, 3);
        
        //pasar el texto a booleano
        boolean activoActual = estadoTexto.equals("Activo");
        PartesLogicas.ProductoDAO dao = new PartesLogicas.ProductoDAO();
        
        // se invierte el estado
        dao.cambiarEstadoDeProducto(idSucursal, idProducto, !activoActual);
        cargarProductos();
    }//GEN-LAST:event_btnDesactivarProductosActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        new VistaAdmin(nombreUsuario,idSucursal).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearProducto;
    private javax.swing.JButton btnDesactivarProductos;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
