/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

import PartesLogicas.ReportesDao;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.ResultSet;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fernan
 */
public class VistaEstadisticaDePartidas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaEstadisticaDePartidas.class.getName());
    private int idSucursal;
    private String nombreJugador;
    /**
     * Creates new form VistaEstadisticaDePartidas
     */
    public VistaEstadisticaDePartidas(int idSucursal) {
        initComponents();
        this.idSucursal = idSucursal;
        this.setLocationRelativeTo(null);
        cargarTabla();
    }
    private void cargarTabla(){ 
        // obtiene el modelo de la tabla para poder modificar sus filas
        DefaultTableModel modelo = (DefaultTableModel) tablaPartidas.getModel();
        modelo.setRowCount(0); // limpia la tabla
        
        // crea el daop para obtener los reportesá
        ReportesDao dao = new ReportesDao();
        
        try {
            // ejecuta la consulta para obtener las partidas de la sucursal
            ResultSet rs = dao.obtenerPartidasSucursal(idSucursal);
            // recorre los resultados obtenidos de la base de datos
            while(rs.next()){
                Object[] fila = {
                    rs.getString("nombre"),
                    rs.getInt("puntaje_total"),
                    rs.getInt("nivel_alcanzado"),
                    rs.getInt("pedidos_completados")
                };
                // agrega la fila a la tabla
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            logger.severe("Error al cargar estadísticas de partidas: " + e.getMessage());

            JOptionPane.showMessageDialog(this,
                    "Error al cargar las estadísticas de partidas");
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPartidas = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaPartidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jugador", "Puntaje", "Nivel Alcanzado", "Pedidos Completados"
            }
        ));
        jScrollPane1.setViewportView(tablaPartidas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 700, 554));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 650, 144, 54));

        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });
        getContentPane().add(btnExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 650, 129, 54));

        jLabel2.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ESTADISTICAS DE PARTIDAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen pegada (2).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VistaAdmin vista = new VistaAdmin(nombreJugador,idSucursal);
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed
    
      
    private void exportarCSV(){
        try {
            // permite al usuario elegir donde guardar el archivo
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Guardar reporte CSV");
            
            int userSeleccion = fileChooser.showSaveDialog(this);
            
            if(userSeleccion == JFileChooser.APPROVE_OPTION){
                File archivo = fileChooser.getSelectedFile();
                
                FileWriter fw = new FileWriter(archivo + ".csv");
                BufferedWriter bw = new BufferedWriter(fw);
                // obtiene el modelo de la tabla
                DefaultTableModel modelo = (DefaultTableModel) tablaPartidas.getModel();
                
                // escribir los encabezados de la tabla
                for (int i = 0; i < modelo.getColumnCount(); i++) {
                    bw.write(modelo.getColumnName(i));
                    if(i< modelo.getColumnCount()-1){
                        bw.write(";");
                    }
                }
                
                bw.newLine();
                
                // recorre todas las filas para exportar los datos
                for (int i = 0; i < modelo.getRowCount(); i++) {
                    for (int j = 0; j < modelo.getColumnCount(); j++) {
                        bw.write(modelo.getValueAt(i, j).toString());
                        
                        if(j < modelo.getColumnCount()-1){
                            bw.write(";");
                        }
                    }
                    bw.newLine();
                }
                bw.close();
                JOptionPane.showMessageDialog(this, "Reporte exportado Correctamente");
            }
        
        } catch (Exception e) {
           
            logger.severe("Error al exportar CSV: " + e.getMessage());

            JOptionPane.showMessageDialog(this,
                    "Error al exportar el reporte");
                }
    }
    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        // TODO add your handling code here:
        exportarCSV();
    }//GEN-LAST:event_btnExportarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPartidas;
    // End of variables declaration//GEN-END:variables
}
