/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

import PartesLogicas.ReportesDao;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author fernan
 */
public class VistaEstadisticasGlobales extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaEstadisticasGlobales.class.getName());

    /**
     * Creates new form VistaEstadisticasGlobales
     */
    public VistaEstadisticasGlobales() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarEstadisticas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTotalPartidas = new javax.swing.JLabel();
        labelPromedioPuntos = new javax.swing.JLabel();
        labelMejorPuntaje = new javax.swing.JLabel();
        labelTotalPedidos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(386, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMejorPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPromedioPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTotalPartidas, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTotalPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(270, 270, 270))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(labelTotalPartidas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(labelPromedioPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(labelMejorPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(labelTotalPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarEstadisticas() throws SQLException{
        ReportesDao dao = new ReportesDao();
        ResultSet rs = dao.obtenerEstadisticasGlobales();
        
        try {

        if(rs.next()){

            labelTotalPartidas.setText("Total partidas: " + rs.getInt("total_partidas"));

            labelPromedioPuntos.setText("Promedio puntos: " + rs.getDouble("promedio_puntos"));

            labelMejorPuntaje.setText("Mejor puntaje: " + rs.getInt("mejor_puntaje"));

            labelTotalPedidos.setText("Pedidos entregados: " + rs.getInt("total_pedidos"));
        }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelMejorPuntaje;
    private javax.swing.JLabel labelPromedioPuntos;
    private javax.swing.JLabel labelTotalPartidas;
    private javax.swing.JLabel labelTotalPedidos;
    // End of variables declaration//GEN-END:variables
}
