/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

import PartesLogicas.ReportesDao;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author fernan
 */
public class VistaEstadisticasGlobales extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaEstadisticasGlobales.class.getName());
    private String nombreJugador;
    /**
     * Creates new form VistaEstadisticasGlobales
     */
    public VistaEstadisticasGlobales() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarEstadisticas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTotalPartidas = new javax.swing.JLabel();
        labelPromedioPuntos = new javax.swing.JLabel();
        labelMejorPuntaje = new javax.swing.JLabel();
        labelTotalPedidos = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelPedidosCancelados = new javax.swing.JLabel();
        labelPedidosNoEntregados = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTotalPartidas.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(labelTotalPartidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 190, 46));

        labelPromedioPuntos.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(labelPromedioPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 179, 42));
        getContentPane().add(labelMejorPuntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 190, 47));

        labelTotalPedidos.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(labelTotalPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 190, 45));

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 680, 130, 60));

        jLabel2.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CONSULTAS DE ESTADISTICAS GLOBALES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 760, 60));
        getContentPane().add(labelPedidosCancelados, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 468, 330, 50));
        getContentPane().add(labelPedidosNoEntregados, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 300, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen pegada (3).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        VistaSuperAdmin vista = new VistaSuperAdmin(nombreJugador);
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed
    
    //obtiene las estadisticas globales del sistema desde la base de datos
    private void cargarEstadisticas() throws SQLException{
        // crea el objeto dao para realizar la consulta
        ReportesDao dao = new ReportesDao();
        //  ejecuta consulta que devuelve las estadisticas globales
        ResultSet rs = dao.obtenerEstadisticasGlobales();
        
        try {
        // verifica si se obtuvo almenos un resultado
        if(rs.next()){

            labelTotalPartidas.setText("Total partidas: " + rs.getInt("total_partidas"));

            labelPromedioPuntos.setText("Promedio puntos: " + rs.getDouble("promedio_puntos"));

            labelMejorPuntaje.setText("Mejor puntaje: " + rs.getInt("mejor_puntaje"));

            labelTotalPedidos.setText("Pedidos entregados: " + rs.getInt("total_pedidos_completados"));
            
            labelPedidosCancelados.setText("Pedidos cancelados: " + rs.getInt("total_pedidos_cancelados"));
            
            labelPedidosNoEntregados.setText("Pedidos no entregados: " + rs.getInt("total_pedidos_no_entregados"));
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar estadísticas");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelMejorPuntaje;
    private javax.swing.JLabel labelPedidosCancelados;
    private javax.swing.JLabel labelPedidosNoEntregados;
    private javax.swing.JLabel labelPromedioPuntos;
    private javax.swing.JLabel labelTotalPartidas;
    private javax.swing.JLabel labelTotalPedidos;
    // End of variables declaration//GEN-END:variables
}
