/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

import LogicaDelJuego.VistaDePartida;

/**
 *
 * @author fernan
 */
public class VistaJugador extends javax.swing.JFrame {
    private String nombreJugador;
    private int idSucursal;
    private int idJugador;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaJugador.class.getName());

    /**
     * Creates new form VistaJugador
     */
    public VistaJugador(int idJugador, String nombreJugador, int idSucursal) {
        initComponents();
        // guarda los tados del jugador
        this.nombreJugador = nombreJugador;
        this.idSucursal= idSucursal;
        this.idJugador = idJugador;
        labelNombreJugador.setText(nombreJugador);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnComenzarPartida = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        labelNombreJugador = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("BIENVENIDO ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 320, 50));

        btnComenzarPartida.setBackground(new java.awt.Color(204, 204, 204));
        btnComenzarPartida.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 24)); // NOI18N
        btnComenzarPartida.setForeground(new java.awt.Color(0, 0, 0));
        btnComenzarPartida.setText("Iniciar Partida");
        btnComenzarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComenzarPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnComenzarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 250, 70));

        btnRegresar.setBackground(new java.awt.Color(204, 204, 204));
        btnRegresar.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 24)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresar.setText("Cerrar Sesion");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 220, 70));

        labelNombreJugador.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 36)); // NOI18N
        getContentPane().add(labelNombreJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 270, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen pegada.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComenzarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComenzarPartidaActionPerformed
        // Verifica que el jugador tenga una sucursal asignada
        if(idSucursal ==0){
            javax.swing.JOptionPane.showMessageDialog(this, "no tiene sucursal asignada");
            return;
        }
        // consulta si la sucursal esta activa
        PartesLogicas.SucursalDAO dao = new PartesLogicas.SucursalDAO();
        boolean activa = dao.estaActiva(idSucursal);
        if(!activa){
            javax.swing.JOptionPane.showMessageDialog(this, "tu sucursal esta inactiva. no puedes jugar");
            return;
        }
        // abre la ventana de la partida
        new VistaDePartida(idJugador, nombreJugador, idSucursal).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnComenzarPartidaActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComenzarPartida;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelNombreJugador;
    // End of variables declaration//GEN-END:variables
}
