/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

import PartesLogicas.Sucursal;
import PartesLogicas.SucursalDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fernan
 */
public class VistaCreadorYModificadorDeSucursal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaCreadorYModificadorDeSucursal.class.getName());
    private String nombreJugador;
    /**
     * Creates new form VistaCreadorYModificadorDeSucursal
     */
    public VistaCreadorYModificadorDeSucursal() {
        initComponents();
        cargarTabla();
    }

    private void cargarTabla(){
        SucursalDAO dao = new SucursalDAO();
        List<Sucursal> lista = dao.obtenerSucursales();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Direccion");
        modelo.addColumn("Estado");
        
        for(Sucursal s: lista){
            modelo.addRow(new Object[]{
                s.getId(),
                s.getNombre(),
                s.getDireccion(),
                s.isEstado() ? "Activa": "Inactiva"
            });
        }
        tblSucursales.setModel(modelo);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrearSucursal = new javax.swing.JButton();
        btnModificarSucursal = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        checkEstado = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSucursales = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrearSucursal.setText("Crear Sucursal");
        btnCrearSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearSucursalActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 690, 180, 52));

        btnModificarSucursal.setText("Modificar Sucursal");
        btnModificarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarSucursalActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificarSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 690, 160, 52));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 213, -1));

        txtDireccion.setText(" ");
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 370, -1));

        checkEstado.setForeground(new java.awt.Color(0, 0, 0));
        checkEstado.setText("Activa");
        getContentPane().add(checkEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 120, 111, 33));

        tblSucursales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSucursales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSucursalesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSucursales);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 1250, 441));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nuevo Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nueva Direccion: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 690, 150, 52));

        jLabel4.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("CREA O MODIFICA UNA SUCURSAL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen pegada (2).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearSucursalActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombre.getText();
        String Direccion = txtDireccion.getText();
        
        if(nombre.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "El Nombre es Obligatorio");
            return;
        }
        SucursalDAO dao = new SucursalDAO();
        boolean creado = dao.crearSucursal(nombre, Direccion);
        
        if(creado){
            javax.swing.JOptionPane.showMessageDialog(this, "Succursal creada");
            cargarTabla();
            limpiarCampos();
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Error al crear sucursal");
        }
    }//GEN-LAST:event_btnCrearSucursalActionPerformed

    private void btnModificarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarSucursalActionPerformed
        // TODO add your handling code here:
        int fila = tblSucursales.getSelectedRow();
        
        if(fila == -1){
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una Sucursal´t");
            return;
        }
        int id = (int) tblSucursales.getValueAt(fila, 0);
        String nombre = txtNombre.getText();
        String direccion = txtDireccion.getText();
        boolean estado = checkEstado.isSelected();
        
        SucursalDAO dao = new SucursalDAO();
        boolean modificado = dao.modificarSucursal(id, nombre, direccion, estado);
        
        if(modificado){
            javax.swing.JOptionPane.showMessageDialog(this, "sucursal modficada correctamente");
            cargarTabla();
            limpiarCampos();
        }else{
           javax.swing.JOptionPane.showMessageDialog(this, "Error al modificar tabla");
        }
    }//GEN-LAST:event_btnModificarSucursalActionPerformed

    private void tblSucursalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSucursalesMouseClicked
        // TODO add your handling code here:
        int fila = tblSucursales.getSelectedRow();
        txtNombre.setText(tblSucursales.getValueAt(fila, 1).toString());
        txtDireccion.setText(tblSucursales.getValueAt(fila, 2).toString());
        
        String estadoTexto = tblSucursales.getValueAt(fila, 3).toString();
        checkEstado.setSelected(estadoTexto.equals("Activa"));
    }//GEN-LAST:event_tblSucursalesMouseClicked

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
         VistaSuperAdmin admin = new VistaSuperAdmin(nombreJugador);
         admin.setLocationRelativeTo(null);
         admin.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
 
    private void limpiarCampos(){
        txtNombre.setText("");
        txtDireccion.setText("");
        checkEstado.setSelected(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearSucursal;
    private javax.swing.JButton btnModificarSucursal;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox checkEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSucursales;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
