/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

import java.sql.SQLException;

/**
 *
 * @author fernan
 */
public class VistaAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaAdmin.class.getName());
    private String nombreJugador;
    private int idSucursal;
    /**
     * Creates new form VistaAdmin
     */
    
    public VistaAdmin(String nombreJugador, int idSucursal) {
        initComponents();
        this.nombreJugador = nombreJugador;
        this.idSucursal = idSucursal;
        labelNombreJugador.setText(nombreJugador);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombreJugador = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGestionarProductos = new javax.swing.JButton();
        btnConsultarEstadisticas = new javax.swing.JButton();
        btnConsultarRankingJugadores = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNombreJugador.setBackground(new java.awt.Color(255, 255, 255));
        labelNombreJugador.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 36)); // NOI18N
        labelNombreJugador.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(labelNombreJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 260, 50));

        jLabel2.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("BIENVENIDO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 220, -1));

        btnGestionarProductos.setText("GESTIONAR PRODUCTOS DEL MENU");
        btnGestionarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarProductosActionPerformed(evt);
            }
        });
        getContentPane().add(btnGestionarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 340, 50));

        btnConsultarEstadisticas.setText("CONSULTAR ESTADISTICAS DE PARTIDAS");
        btnConsultarEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEstadisticasActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultarEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 340, 50));

        btnConsultarRankingJugadores.setText("CONSULTAR EL RANKING DE JUGADORES");
        btnConsultarRankingJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarRankingJugadoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultarRankingJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 340, 50));

        btnSalir.setText("Cerrar Sesion");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen pegada.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGestionarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarProductosActionPerformed
        // TODO add your handling code here:
        VistaGestionDeProductos iniciar= new VistaGestionDeProductos(idSucursal);
        iniciar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionarProductosActionPerformed

    private void btnConsultarEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEstadisticasActionPerformed
        new VistaEstadisticaDePartidas(idSucursal).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultarEstadisticasActionPerformed

    private void btnConsultarRankingJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarRankingJugadoresActionPerformed
        try {
            VistaEstadisticaDeJugadores vista = new VistaEstadisticaDeJugadores(idSucursal);
            vista.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            System.getLogger(VistaAdmin.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
       
    }//GEN-LAST:event_btnConsultarRankingJugadoresActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarEstadisticas;
    private javax.swing.JButton btnConsultarRankingJugadores;
    private javax.swing.JButton btnGestionarProductos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelNombreJugador;
    // End of variables declaration//GEN-END:variables
}
