/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

import java.sql.SQLException;

/**
 *
 * @author fernan
 */
public class VistaSuperAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaSuperAdmin.class.getName());
    private String nombreJugador;
    /**
     * Creates new form VistaSuperAdmin
     */
    public VistaSuperAdmin(String nombreJugador) {
        initComponents();
        this.nombreJugador = nombreJugador;
        labelNombreJugador.setText(nombreJugador);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnCrearYModificarSucursales = new javax.swing.JButton();
        btnCrearUsuaios = new javax.swing.JButton();
        btnAsignarUsuarioASucursal = new javax.swing.JButton();
        btnConsultarEstadisticasGlobales = new javax.swing.JButton();
        btnVisualizarRankingGeneral = new javax.swing.JButton();
        btnAdministrarParametrosGenerales = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        labelNombreJugador = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Bienvenido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 300, 50));

        btnCrearYModificarSucursales.setBackground(new java.awt.Color(204, 204, 204));
        btnCrearYModificarSucursales.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 24)); // NOI18N
        btnCrearYModificarSucursales.setForeground(new java.awt.Color(0, 0, 0));
        btnCrearYModificarSucursales.setText("Crear y modificar sucursales");
        btnCrearYModificarSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearYModificarSucursalesActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearYModificarSucursales, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 430, 50));

        btnCrearUsuaios.setBackground(new java.awt.Color(204, 204, 204));
        btnCrearUsuaios.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 24)); // NOI18N
        btnCrearUsuaios.setForeground(new java.awt.Color(0, 0, 0));
        btnCrearUsuaios.setText("Registrar Usuarios Nuevos");
        btnCrearUsuaios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsuaiosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearUsuaios, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 430, 50));

        btnAsignarUsuarioASucursal.setBackground(new java.awt.Color(204, 204, 204));
        btnAsignarUsuarioASucursal.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 24)); // NOI18N
        btnAsignarUsuarioASucursal.setForeground(new java.awt.Color(0, 0, 0));
        btnAsignarUsuarioASucursal.setText("Asignar Usuario a  Sucursales");
        btnAsignarUsuarioASucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarUsuarioASucursalActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsignarUsuarioASucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 430, 50));

        btnConsultarEstadisticasGlobales.setBackground(new java.awt.Color(204, 204, 204));
        btnConsultarEstadisticasGlobales.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 24)); // NOI18N
        btnConsultarEstadisticasGlobales.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultarEstadisticasGlobales.setText("Consultar Estadistica Globales");
        btnConsultarEstadisticasGlobales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEstadisticasGlobalesActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultarEstadisticasGlobales, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, 50));

        btnVisualizarRankingGeneral.setBackground(new java.awt.Color(204, 204, 204));
        btnVisualizarRankingGeneral.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 24)); // NOI18N
        btnVisualizarRankingGeneral.setForeground(new java.awt.Color(0, 0, 0));
        btnVisualizarRankingGeneral.setText("Visualizar Ranking General De Jugadores");
        btnVisualizarRankingGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarRankingGeneralActionPerformed(evt);
            }
        });
        getContentPane().add(btnVisualizarRankingGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 610, 50));

        btnAdministrarParametrosGenerales.setBackground(new java.awt.Color(204, 204, 204));
        btnAdministrarParametrosGenerales.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 24)); // NOI18N
        btnAdministrarParametrosGenerales.setForeground(new java.awt.Color(0, 0, 0));
        btnAdministrarParametrosGenerales.setText("Administrar Parametros Generales Del Juego");
        btnAdministrarParametrosGenerales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarParametrosGeneralesActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdministrarParametrosGenerales, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, 50));

        btnCerrarSesion.setBackground(new java.awt.Color(204, 204, 204));
        btnCerrarSesion.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 24)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, -1, -1));

        labelNombreJugador.setBackground(new java.awt.Color(0, 0, 0));
        labelNombreJugador.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 36)); // NOI18N
        labelNombreJugador.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(labelNombreJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 340, 40));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen pegada.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 870, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsignarUsuarioASucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarUsuarioASucursalActionPerformed
        VistaAsignarUsuarioASucursal asiganar = new VistaAsignarUsuarioASucursal();
        asiganar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAsignarUsuarioASucursalActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnCrearYModificarSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearYModificarSucursalesActionPerformed
      VistaCreadorYModificadorDeSucursal vista = new VistaCreadorYModificadorDeSucursal();
      vista.setLocationRelativeTo(this);
      vista.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnCrearYModificarSucursalesActionPerformed

    private void btnCrearUsuaiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsuaiosActionPerformed
        FrmUsuario frm = new FrmUsuario();
        frm.setLocationRelativeTo(this);
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCrearUsuaiosActionPerformed

    private void btnConsultarEstadisticasGlobalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEstadisticasGlobalesActionPerformed
        try {
            VistaEstadisticasGlobales vista = new VistaEstadisticasGlobales();
            vista.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            System.getLogger(VistaSuperAdmin.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnConsultarEstadisticasGlobalesActionPerformed

    private void btnVisualizarRankingGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarRankingGeneralActionPerformed
        try {
            VistaRankingGeneralDeJugadores vista = new VistaRankingGeneralDeJugadores();
            vista.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            System.getLogger(VistaSuperAdmin.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
           
    }//GEN-LAST:event_btnVisualizarRankingGeneralActionPerformed

    private void btnAdministrarParametrosGeneralesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarParametrosGeneralesActionPerformed
        VistaModificarParametrosGenerales vista = new VistaModificarParametrosGenerales();
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdministrarParametrosGeneralesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrarParametrosGenerales;
    private javax.swing.JButton btnAsignarUsuarioASucursal;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnConsultarEstadisticasGlobales;
    private javax.swing.JButton btnCrearUsuaios;
    private javax.swing.JButton btnCrearYModificarSucursales;
    private javax.swing.JButton btnVisualizarRankingGeneral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelNombreJugador;
    // End of variables declaration//GEN-END:variables
}
