/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

import PartesLogicas.ParametrosJuego;
import PartesLogicas.ParametrosJuegoDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fernan
 */
public class VistaModificarParametrosGenerales extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaModificarParametrosGenerales.class.getName());
    private String nombreJugador;
    /**
     * Creates new form VistaModificarParametrosGenerales
     */
    public VistaModificarParametrosGenerales() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarSucursales();
        llenarCombos();
        
        jTable1.getSelectionModel().addListSelectionListener(e-> cargarParametros());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnGuardarCambios = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comboBoxNivel1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        comboboxNivel2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        comboBoxNivel3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sucursal", "Tiempo Nivel 1", "Tiempo Nivel 2", "Tiempo Nivel 3"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 940, 470));

        jLabel1.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 24)); // NOI18N
        jLabel1.setText("CONFIGURACION DE PARAMETROS POR SUCURSAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        btnGuardarCambios.setText("Guardar Cambios");
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 730, -1, 40));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 730, 120, 40));

        jLabel2.setText("Parametros Nivel 1: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 640, -1, -1));

        comboBoxNivel1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboBoxNivel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 640, -1, -1));

        jLabel3.setText("Parametros nivel 2; ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 650, -1, -1));

        comboboxNivel2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboboxNivel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 650, -1, -1));

        jLabel4.setText("Parametros nivel 3:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 650, -1, -1));

        comboBoxNivel3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboBoxNivel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 650, -1, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // cargar los paramteros de la sucursal seleccionada
    private void cargarParametros(){
        // obtiene la fila seleccionada en la tabla
        int fila = jTable1.getSelectedRow();

        if(fila == -1){
            return;
        }
        // obtiene los tiemos de cada nivel desde la tabla
        int t1 = Integer.parseInt(jTable1.getValueAt(fila,1).toString());
        int t2 = Integer.parseInt(jTable1.getValueAt(fila,2).toString());
        int t3 = Integer.parseInt(jTable1.getValueAt(fila,3).toString());
        // muestra los valores en el comboBox
        comboBoxNivel1.setSelectedItem(String.valueOf(t1));
        comboboxNivel2.setSelectedItem(String.valueOf(t2));
        comboBoxNivel3.setSelectedItem(String.valueOf(t3));
    }
    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        // obtiene la fila seleccionada
        int fila = jTable1.getSelectedRow();
        
        // verifica que se haya seleccionado una sucursal
        if(fila == -1){
            JOptionPane.showMessageDialog(this, "Seeccione una sucursal");
            return;
        }
        
        String nombreSucursal = jTable1.getValueAt(fila, 0).toString();
        // obtiene los valores seleccionados en el combobox
        int t1 = Integer.parseInt(comboBoxNivel1.getSelectedItem().toString());
        int t2 = Integer.parseInt(comboboxNivel2.getSelectedItem().toString());
        int t3 = Integer.parseInt(comboBoxNivel3.getSelectedItem().toString());
        
        PartesLogicas.SucursalDAO daoSucursal = new PartesLogicas.SucursalDAO();
        int idSucursal = daoSucursal.obtenerIdPorNombre(nombreSucursal);
        
        // obtiene el id de la sucursal 
        ParametrosJuegoDAO daoParametros = new ParametrosJuegoDAO();
        daoParametros.guardarOActualizarParametros(idSucursal,t1,t2,t3);
        JOptionPane.showMessageDialog(this, "Parametros Guardados");
        
        cargarSucursales();
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        VistaSuperAdmin vista = new VistaSuperAdmin(nombreJugador);
        vista.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnVolverActionPerformed
    
    private void llenarCombos(){
        
        comboBoxNivel1.removeAllItems();
        comboboxNivel2.removeAllItems();
        comboBoxNivel3.removeAllItems();
        // tiempos disponivles para cada nivel del juego
        int[] tiempos = {10,15,20,25,30,35,40,45,50,60};
        // agrega cada tiempo a los combobox
        for(int t : tiempos){
            comboBoxNivel1.addItem(String.valueOf(t));
            comboboxNivel2.addItem(String.valueOf(t));
            comboBoxNivel3.addItem(String.valueOf(t));
        }
    }
    private void cargarSucursales(){
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); // limpia la tabla antes de cargar nuevos datos
        
        PartesLogicas.SucursalDAO daoSucursal = new PartesLogicas.SucursalDAO();
        java.util.List<PartesLogicas.Sucursal> lista = daoSucursal.obtenerSucursales();
        
        PartesLogicas.ParametrosJuegoDAO daoParametros = new PartesLogicas.ParametrosJuegoDAO();
        
        for(PartesLogicas.Sucursal s : lista){
            ParametrosJuego p =daoParametros.obtenerParametros(s.getId());
            // agrega cada sucursal y sus parametros a la tabla
            modelo.addRow(new Object[]{
                s.getNombre(),
                p.getTiempoNivel1(),
                p.getTiempoNivel2(),
                p.getTiempoNivel3(),
            });
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> comboBoxNivel1;
    private javax.swing.JComboBox<String> comboBoxNivel3;
    private javax.swing.JComboBox<String> comboboxNivel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
