/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

import PartesLogicas.ReportesDao;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.ResultSet;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fernan
 */
public class VistaEstadisticaDePartidas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaEstadisticaDePartidas.class.getName());
    private int idSucursal;
    private String nombreJugador;
    /**
     * Creates new form VistaEstadisticaDePartidas
     */
    public VistaEstadisticaDePartidas(int idSucursal) {
        initComponents();
        this.idSucursal = idSucursal;
        cargarTabla();
    }
    private void cargarTabla(){
        DefaultTableModel modelo = (DefaultTableModel) tablaPartidas.getModel();
        modelo.setRowCount(0); // limpia la tabla
        
        ReportesDao dao = new ReportesDao();
        
        try {
            ResultSet rs = dao.obtenerPartidasSucursal(idSucursal);
            while(rs.next()){
                Object[] fila = {
                    rs.getString("nombre"),
                    rs.getInt("puntaje_total"),
                    rs.getInt("nivel_alcanzado"),
                    rs.getInt("pedidos_completados")
                };
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPartidas = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaPartidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jugador", "Puntaje", "Nivel Alcanzado", "Pedidos Completados"
            }
        ));
        jScrollPane1.setViewportView(tablaPartidas);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(258, 258, 258))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(btnExportar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VistaAdmin vista = new VistaAdmin(nombreJugador,idSucursal);
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed
    
      
    private void exportarCSV(){
        try {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Guardar reporte CSV");
            
            int userSeleccion = fileChooser.showSaveDialog(this);
            
            if(userSeleccion == JFileChooser.APPROVE_OPTION){
                File archivo = fileChooser.getSelectedFile();
                
                FileWriter fw = new FileWriter(archivo + ".csv");
                BufferedWriter bw = new BufferedWriter(fw);
                
                DefaultTableModel modelo = (DefaultTableModel) tablaPartidas.getModel();
                
                // escribir los encabezados
                for (int i = 0; i < modelo.getColumnCount(); i++) {
                    bw.write(modelo.getColumnName(i));
                    if(i< modelo.getColumnCount()-1){
                        bw.write(";");
                    }
                }
                
                bw.newLine();
                
                // escribir las filas 
                for (int i = 0; i < modelo.getRowCount(); i++) {
                    for (int j = 0; j < modelo.getColumnCount(); j++) {
                        bw.write(modelo.getValueAt(i, j).toString());
                        
                        if(j < modelo.getColumnCount()-1){
                            bw.write(";");
                        }
                    }
                    bw.newLine();
                }
                bw.close();
                JOptionPane.showMessageDialog(this, "Reporte exportado Correctamente");
            }
        
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        // TODO add your handling code here:
        exportarCSV();
    }//GEN-LAST:event_btnExportarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPartidas;
    // End of variables declaration//GEN-END:variables
}
