/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fernan
 */
public class VistaEstadisticaDeJugadores extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaEstadisticaDeJugadores.class.getName());
    private int idSucursal;
    private String nombreJugador;
    /**
     * Creates new form VistaEstadisticaDeJugadores
     */
    public VistaEstadisticaDeJugadores(int idSucursal) throws SQLException {
        initComponents();
        this.idSucursal = idSucursal;
        cargarRanking();
        
    }
    
    private void cargarRanking() throws SQLException{
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        
        PartesLogicas.ReportesDao dao = new PartesLogicas.ReportesDao();
        ResultSet rs = dao.obtenerRankingSucursal(idSucursal);
        
        int posicion = 1;
        try {
            while(rs.next()){
                String nombre = rs.getString("nombre");
                int puntos = rs.getInt("puntos");
                int nivel = rs.getInt("nivel");
                int partidas = rs.getInt("partidas_jugadas");
                int mejor = rs.getInt("mejor_puntaje");
                
                modelo.addRow(new Object[]{
                    nombre,
                    puntos,
                    nivel,
                    partidas,
                    mejor
                });
                posicion++;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Jugador", "Puntos", "Nivel", "Partidas Jugadas", "MejorPuntaje"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 624, 561));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 680, 150, 50));

        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });
        getContentPane().add(btnExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 680, 150, 50));

        jLabel2.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("RANKING DE JUGADORES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen pegada (2).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VistaAdmin vista = new VistaAdmin(nombreJugador,idSucursal);
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        // TODO add your handling code here:
        exportarCSV();
    }//GEN-LAST:event_btnExportarActionPerformed
    
    private void exportarCSV(){
        try {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Guardar reporte CSV");
            
            int userSeleccion = fileChooser.showSaveDialog(this);
            
            if(userSeleccion == JFileChooser.APPROVE_OPTION){
                File archivo = fileChooser.getSelectedFile();
                
                FileWriter fw = new FileWriter(archivo + ".csv");
                BufferedWriter bw = new BufferedWriter(fw);
                
                DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
                
                // escribir los encabezados
                for (int i = 0; i < modelo.getColumnCount(); i++) {
                    bw.write(modelo.getColumnName(i));
                    if(i< modelo.getColumnCount()-1){
                        bw.write(";");
                    }
                }
                
                bw.newLine();
                
                // escribir las filas 
                for (int i = 0; i < modelo.getRowCount(); i++) {
                    for (int j = 0; j < modelo.getColumnCount(); j++) {
                        bw.write(modelo.getValueAt(i, j).toString());
                        
                        if(j < modelo.getColumnCount()-1){
                            bw.write(";");
                        }
                    }
                    bw.newLine();
                }
                bw.close();
                JOptionPane.showMessageDialog(this, "Reporte exportado Correctamente");
            }
        
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
