/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

import PartesLogicas.Sucursal;
import PartesLogicas.SucursalDAO;
import PartesLogicas.Usuario;
import PartesLogicas.UsuarioDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fernan
 */
public class VistaAsignarUsuarioASucursal extends javax.swing.JFrame {
    private String nombreJugador;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaAsignarUsuarioASucursal.class.getName());

    /**
     * Creates new form VistaAsignarUsuarioASucursal
     */
    public VistaAsignarUsuarioASucursal() {
        initComponents();
        setLocationRelativeTo(null);
        cargarUsuarios();
        cargarSucursales();
      
    }
    private void cargarUsuarios(){
        UsuarioDAO dao = new UsuarioDAO();
        List<Usuario> lista = dao.obtenerUsuarioSinSucursal();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Username");
        modelo.addColumn("Rol");
        
        for(Usuario u : lista){
            modelo.addRow(new Object[]{
                u.getId(),
                u.getNombre(),
                u.getUsername(),
                u.getRol()
            });
        }
        jTable1.setModel(modelo);
        
    }
    
    private void cargarSucursales(){
        SucursalDAO dao = new SucursalDAO();
        List<Sucursal> lista = dao.obtenerSucursales();
        jComboBox1.removeAllItems();
        for(Sucursal s: lista){
            jComboBox1.addItem(s);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnAsiganar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 130, 932, -1));

        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 602, 133, -1));

        jLabel1.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Seleccione Sucursal: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 600, -1, -1));

        btnAsiganar.setText("Asiganar");
        btnAsiganar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsiganarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsiganar, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 688, 119, 37));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 688, 118, 37));

        jLabel3.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ASIGNA UN USUARIO A SUCURSAL");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen pegada (3).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsiganarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsiganarActionPerformed
       int fila = jTable1.getSelectedRow();
       if(fila == -1){
           javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un usuario");
           return;
       }
       int idUsuario = (int) jTable1.getValueAt(fila, 0);
       Sucursal sucursalSeleccionada =(Sucursal) jComboBox1.getSelectedItem();
       if(sucursalSeleccionada == null){
           javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una Sucursal");
           return;
       }
       
       int idSucursal = sucursalSeleccionada.getId();
       
       UsuarioDAO dao = new UsuarioDAO();
       boolean asignado =dao.asignarUsuarioSucursal(idUsuario, idSucursal);
       if(asignado){
           javax.swing.JOptionPane.showMessageDialog(this, "Usuario asignado correctamente");
           cargarUsuarios();
       }else{
           javax.swing.JOptionPane.showMessageDialog(this, "Error al asignar usuario a sucursal");
       }
    }//GEN-LAST:event_btnAsiganarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VistaSuperAdmin admin = new VistaSuperAdmin(nombreJugador);
         admin.setLocationRelativeTo(null);
         admin.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsiganar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<Sucursal> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
