/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

/**
 *
 * @author fernan
 */
public class VistaSuperAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaSuperAdmin.class.getName());
    private String nombreJugador;
    /**
     * Creates new form VistaSuperAdmin
     */
    public VistaSuperAdmin(String nombreJugador) {
        initComponents();
        this.nombreJugador = nombreJugador;
        labelNombreJugador.setText(nombreJugador);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnCrearYModificarSucursales = new javax.swing.JButton();
        btnCrearUsuaios = new javax.swing.JButton();
        btnAsignarUsuarioASucursal = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        labelNombreJugador = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Bienvenido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 300, 50));

        btnCrearYModificarSucursales.setBackground(new java.awt.Color(204, 204, 204));
        btnCrearYModificarSucursales.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 24)); // NOI18N
        btnCrearYModificarSucursales.setForeground(new java.awt.Color(0, 0, 0));
        btnCrearYModificarSucursales.setText("Crear y modificar sucursales");
        btnCrearYModificarSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearYModificarSucursalesActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearYModificarSucursales, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 430, 60));

        btnCrearUsuaios.setBackground(new java.awt.Color(204, 204, 204));
        btnCrearUsuaios.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 24)); // NOI18N
        btnCrearUsuaios.setForeground(new java.awt.Color(0, 0, 0));
        btnCrearUsuaios.setText("Registrar Usuarios Nuevos");
        btnCrearUsuaios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsuaiosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearUsuaios, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 380, 50));

        btnAsignarUsuarioASucursal.setBackground(new java.awt.Color(204, 204, 204));
        btnAsignarUsuarioASucursal.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 24)); // NOI18N
        btnAsignarUsuarioASucursal.setForeground(new java.awt.Color(0, 0, 0));
        btnAsignarUsuarioASucursal.setText("Asignar Usuario a  Sucursales");
        btnAsignarUsuarioASucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarUsuarioASucursalActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsignarUsuarioASucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 430, 50));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Consultar Estadistica Globales");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, 50));

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Visualizar Ranking General De Jugadores");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, 50));

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("Administrar Parametros Generales Del Juego");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, 50));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 580, -1, -1));

        labelNombreJugador.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 24)); // NOI18N
        getContentPane().add(labelNombreJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 340, 40));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Ubuntu Sans Mono", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen pegada.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsignarUsuarioASucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarUsuarioASucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsignarUsuarioASucursalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCrearYModificarSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearYModificarSucursalesActionPerformed
      VistaCreadorYModificadorDeSucursal vista = new VistaCreadorYModificadorDeSucursal();
      vista.setLocationRelativeTo(this);
      vista.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnCrearYModificarSucursalesActionPerformed

    private void btnCrearUsuaiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsuaiosActionPerformed
        FrmUsuario frm = new FrmUsuario();
        frm.setLocationRelativeTo(this);
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCrearUsuaiosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarUsuarioASucursal;
    private javax.swing.JButton btnCrearUsuaios;
    private javax.swing.JButton btnCrearYModificarSucursales;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelNombreJugador;
    // End of variables declaration//GEN-END:variables
}
