/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LogicaDelJuego;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JProgressBar;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author fernan
 */
public class VistaDePartida extends javax.swing.JFrame {
    private final int MAX_PEDIDOS = 10;
    private java.util.List<javax.swing.Timer> timers = new java.util.ArrayList<>();
    private java.util.Random random = new java.util.Random();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaDePartida.class.getName());

    /**
     * Creates new form VistaDePartida
     */
    public VistaDePartida() {
        initComponents();
        configurarTabla();
        configurarBarra();
        iniciarGeneradorPedidos();
    }
    
    private void iniciarGeneradorPedidos() {

    javax.swing.Timer generador = new javax.swing.Timer(4000, e -> {

        if (jTable1.getRowCount() < MAX_PEDIDOS) {
            generarPedido();
        }

    });

    generador.start();
}
    private void generarPedido() {

    String[] productos = {"Pizza", "Taco", "Hamburguesa", "HotDog"};
    String productoAleatorio = productos[random.nextInt(productos.length)];

    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

    int tiempoInicial = 60 + random.nextInt(41); // entre 60 y 100

    modelo.addRow(new Object[]{productoAleatorio, "RECIBIDO", tiempoInicial});

    int nuevaFila = modelo.getRowCount() - 1;

    iniciarTiempoFila(nuevaFila);
}
    private void iniciarTiempoFila(int fila) {

    javax.swing.Timer timer = new javax.swing.Timer(200, null);

    timer.addActionListener(e -> {

        int tiempoActual = (int) jTable1.getValueAt(fila, 2);
        String estado = (String) jTable1.getValueAt(fila, 1);

        if (estado.equals("ENTREGADO") || 
            estado.equals("CANCELADO") || 
            estado.equals("NO_ENTREGADO")) {
            timer.stop();
            return;
        }

        if (tiempoActual > 0) {
            jTable1.setValueAt(tiempoActual - 1, fila, 2);
        } else {
            jTable1.setValueAt("NO_ENTREGADO", fila, 1);
            timer.stop();
        }

    });

    timers.add(timer);
    timer.start();
}
    private void configurarTabla() {

    DefaultTableModel modelo = new DefaultTableModel(
        new Object[][] {
            {"Pizza", "RECIBIDO", 100},
            {"Taco", "RECIBIDO", 100}
        },
        new String[] {"Producto", "Estado", "Tiempo"}
    ) {
        @Override
        public Class<?> getColumnClass(int columnIndex) {
            if (columnIndex == 2) return Integer.class;
            return Object.class;
        }
    };

    jTable1.setModel(modelo);
}
    class ProgressBarRenderer extends JProgressBar implements TableCellRenderer {

    public ProgressBarRenderer() {
        setMinimum(0);
        setMaximum(100);
        setStringPainted(false);
    }

    @Override
    public Component getTableCellRendererComponent(
            JTable table, Object value, boolean isSelected,
            boolean hasFocus, int row, int column) {

        int tiempo = (Integer) value;
        setValue(tiempo);

        if (tiempo > 60) {
            setForeground(Color.GREEN);
        } else if (tiempo > 30) {
            setForeground(Color.ORANGE);
        } else {
            setForeground(Color.RED);
        }

        return this;
    }
}
    private void configurarBarra() {
    jTable1.getColumn("Tiempo")
           .setCellRenderer(new ProgressBarRenderer());
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnCambiarDeEstado = new javax.swing.JButton();
        btnCancelarPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Producto", "Estado", "Tiempo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCambiarDeEstado.setText("Avanzar estado");
        btnCambiarDeEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarDeEstadoActionPerformed(evt);
            }
        });
        jPanel3.add(btnCambiarDeEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        btnCancelarPedido.setText("Cancelar pedido");
        btnCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPedidoActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1098, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(339, 339, 339))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiarDeEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarDeEstadoActionPerformed
        
    int fila = jTable1.getSelectedRow();

    if (fila == -1) {
        return; // no hay selección
    }

    String estadoActual = (String) jTable1.getValueAt(fila, 1);

    switch (estadoActual) {

        case "RECIBIDO":
            jTable1.setValueAt("EN_PREPARACION", fila, 1);
            break;

        case "EN_PREPARACION":
            jTable1.setValueAt("LISTO", fila, 1);
            break;

        case "LISTO":
            jTable1.setValueAt("ENTREGADO", fila, 1);
            break;

        case "ENTREGADO":
        case "NO_ENTREGADO":
        case "CANCELADO":
            // no hacer nada
            break;
    }
    }//GEN-LAST:event_btnCambiarDeEstadoActionPerformed

    private void btnCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPedidoActionPerformed
        // TODO add your handling code here:
        
    int fila = jTable1.getSelectedRow();

    if (fila == -1) {
        return; // No hay selección
    }

    String estadoActual = (String) jTable1.getValueAt(fila, 1);

    // Si ya terminó, no hacer nada
    if (estadoActual.equals("ENTREGADO") ||
        estadoActual.equals("NO_ENTREGADO") ||
        estadoActual.equals("CANCELADO")) {
        return;
    }

    // Cambiar estado
    jTable1.setValueAt("CANCELADO", fila, 1);

    // Opcional: poner tiempo en 0
    jTable1.setValueAt(0, fila, 2);
    }//GEN-LAST:event_btnCancelarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaDePartida().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarDeEstado;
    private javax.swing.JButton btnCancelarPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
